modLoader="javafml"
loaderVersion="[47,)" # поддерживает Forge 47.x (MC 1.20.1)
license="MIT"
displayURL="discord.gg/NREy5ePYcJ"

[[mods]]
modId="webdisc"
version="${version}"
displayName="WebDisc"
authors="Zoritism"
description='''
webdisc
'''
logoFile = "icon.png"



[[dependencies.webdisc]]
modId="forge"
mandatory=true
versionRange="[47.3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.webdisc]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"