modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://discord.gg/DMmTw9wm https://t.me/Zoritism"
credits="by ${mod_authors}"
authors="${mod_authors}"
description="${mod_description}"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.webdisc]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.webdisc]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration