modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://discord.gg/DMmTw9wm https://t.me/Zoritism"
credits="by ${mod_authors}"
authors="${mod_authors}"
description="${mod_description}"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration